//FLAGS

//FLAGS NIVEL DE ACESSO
#define PERMISSAO_ABRIR_PORTA 0
#define PERMISSAO_REQUERIMENTO_HISTORICO 1
#define PERMISSAO_REQUERIMENTO_STATUS_ATUAL 2
#define PERMISSAO_RECONFIGURAR_PROPRIA_CONTA 3
#define PERMISSAO_RECONFIGURAR_PIC 4  
#define PERMISSAO_RECONFIGURAR_MODULO 5
#define PERMISSAO_MUDAR_SENHA_OUTRAS_CONTAS 6
#define PERMISSAO_MUDAR_PROPRIA_SENHA 7

//FLAGS_1;CORRESPONDÊNCIA DE BITS

#define ERRO_VALOR_PARAMETRO 0
#define ERRO_SESSAO_EXPIRADA 1
#define ERRO_IDENTIF_CONTA 2
#define ERRO_NIVEL_DE_ACESSO 3
#define ERRO_COMUNICACAO 4  
#define ERRO_ABERTURA 5
#define ERRO_SENHA 6
#define ERRO_PROTOCOLO 7

//FLAGS_2 CORRESPONDENCIA DE BITS
#define ENVIAR 0
#define RECEBER 1
#define DEBOUNCE 3
#define MODO_T9 4
#define MAIUSCULA 5
#define MODO_DEBUG_ON 6
#define EXIBIR 7

//FLAGS_3 CORRESPONDENCIA DE BITS
#define ATUALIZAR_HORA_DISPLAY 0
#define ATUALIZAR_SENHA_DISPLAY 1
#define MODO_BT 2
#define MODO_TECLADO 3